### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Increase code coverage by adding tests in Uncovered lines.

### CODE REVIEW

**Review by avorima — COMMENTED** [review]
Please add a comment documenting the validation webhook behavior for MTU on the API type. I'm especially curious why 1 is allowed

**Comment by wikkyk** [comment]
@avorima does ad07179ac59aedc006ed3595028b98914cf2b982 address your concern?
@mcbenjemaa please make the commit message more informative (explain what tests are added).

**Comment by avorima** [comment]
> @avorima does [ad07179](https://github.com/ionos-cloud/cluster-api-provider-proxmox/commit/ad07179ac59aedc006ed3595028b98914cf2b982) address your concern? @mcbenjemaa please make the commit message more informative (explain what tests are added).

The info should be user visible. The special case for 1 as well as the validation the at least 1000. The markers are not enough

**Comment by mcbenjemaa** [comment]
@avorima, if everything is okay, we can include this in v0.2 Release

**Review by avorima — APPROVED** [review]

**Pull request merged**
