### PR TITLE
feat(gateway-optional): This commit makes gw definition optional for additionalNetworkDevices

### PR DESCRIPTION
**Pull request by CiraciNicolo**
*Description of changes:*

There is no need to have a mandatory gateway for secondary network interfaces, this commit edits the validation and go template that is in charge of generating the cloudinit files.

*Testing performed:*

Bootstrapped two machines: 
- one with additional device and no gw defined 
- one without additional device

Both machine got provisioned

### CODE REVIEW

**Comment by CiraciNicolo** [comment]
It would be possibile to have access to the SonarQube report? 

Thanks.

**Comment by mcbenjemaa** [comment]
thank you, i will check this

**Comment by mcbenjemaa** [comment]
Can you share the yaml you used for testing?

**Review by mcbenjemaa — APPROVED** [review]
LGTM

**Comment by CiraciNicolo** [comment]
I merged the main branch into my feature to check eventual issues, probably we need to re-approve workflow 😊

**Comment by CiraciNicolo** [comment]
> Can you share the yaml you used for testing?

Hi! Sorry for the delay, you can find below the manifests used - I will provide only the relative manifest and not the whole cluster definition

```yaml
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: GlobalInClusterIPPool
metadata:
  name: ippool
spec:
  addresses:
    - 10.10.10.4-10.10.10.254
  prefix: 24
---
kind: ProxmoxMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "workers"
spec:
  template:
    spec:
      sourceNode: "source-node"
      templateID: 1001
      format: "qcow2"
      full: true
      numSockets: 1
      numCores: 4
      memoryMiB: 4096
      disks:
        bootVolume:
          disk: virtio0
          sizeGb: 100
      network:
        default:
          bridge: vmbr0
        additionalDevices:
          - bridge: vmbr0
            name: net1
            ipv4PoolRef:
              apiGroup: ipam.cluster.x-k8s.io
              kind: GlobalInClusterIPPool
              name: ippool
```

**Pull request merged**
